### ISSUE TITLE
container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by filiprafaj** [argoproj-labs/argocd-rbac-operator#15]
deployment manifest obtained using `make build-installer` has
```
      securityContext:
        runAsNonRoot: true
```
therefore it wont run with the image built using _release.Dockerfile_ (e.g. _quay.io/argoprojlabs/argocd-rbac-operator:v0.1.2_) as it is `FROM scratch`

> Error: container has runAsNonRoot and image will run as root

**Comment by ggkhrmv** [comment]
thank you, i'll look into it :)

**Comment by ggkhrmv** [comment]
@filiprafaj can u please describe a way to reproduce the bug, so I can dig deeper? :)
