### ISSUE TITLE
sa argocd-rbac-operator-controller-manager trying to list configmaps at the cluster scope

### ISSUE THREAD

**Issue by filiprafaj** [argoproj-labs/argocd-rbac-operator#17]
when trying to run the operator I get:

> W1212 18:17:35.941862       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:argocd:argocd-rbac-operator-controller-manager" cannot list resource "configmaps" in API group "" at the cluster scope
E1212 18:17:35.941892       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:argocd:argocd-rbac-operator-controller-manager" cannot list resource "configmaps" in API group "" at the cluster scope

as I said [here](https://github.com/argoproj-labs/argocd-rbac-operator/pull/16) changing the operator so that it works only with cm in the same namespace is needed

**Comment by ggkhrmv** [comment]
Hi @filiprafaj, could you describe how you're running the operator? :) so I can reproduce this bug

**Comment by ggkhrmv** [comment]
@filiprafaj I've found the issue, the role for the argocd rbac CM is correct, but kustomize overwrites the default  argocd namespace (argocd), that's why the operator cant list the CM

**Comment by filiprafaj** [comment]
this is how I get the resources, so the argocd namespace should be there (see the sed)
```
git clone https://github.com/argoproj-labs/argocd-rbac-operator.git
cd argocd-rbac-operator
sed -i 's/namespace: argocd-rbac-operator-system/namespace: argocd/' config/default/kustomization.yaml
make build-installer
cd ..
mkdir -p stage
cat ./argocd-rbac-operator/dist/install.yaml | \
 docker container run \
 -i --rm \
 -v $(pwd):/code \
        --user $(id -u):$(id -g) \
 -w /code looztra/kubesplit \
 -o ./stage \
 --no-resource-prefix
rm -rf argocd-rbac-operator
rm ./stage/namespace--argocd.yml
```
