### ISSUE TITLE
[docs] add description for CRD fields

### ISSUE THREAD

**Issue by ggkhrmv** [argoproj-labs/argocd-rbac-operator#5]
### Is your task related to a problem? Please describe.

The fields of CRDs (doc.crds.dev) don't have description, which could be confusing for users.

### Describe the solution you'd like

Added descriptions for CRD fields.

### Additional context

![image](https://github.com/user-attachments/assets/00b36f99-2ce5-432e-98f1-664ad0870ec3)

**Comment by jameskim0987** [comment]
I can take a look at this issue

**Comment by ggkhrmv** [comment]
> I can take a look at this issue

that would be great, thank you :)

**Comment by jameskim0987** [comment]
@ggkhrmv Hi, I have a question. So far, I have added temporary `TODO` placeholders to mark the location for the descriptions. Now, however, I'm stuck observing the changes locally. Could you help me how I can see and test the doc changes locally? ( it seems https://github.com/crdsdev/doc is not that active anymore, I was not able to find info on any of their docs ).

**Comment by ggkhrmv** [comment]
> @ggkhrmv I have a question. So far, I have added temporary `TODO` placeholders to mark the location for the descriptions. Now, however, I'm stuck observing the doc.crds.dev changes locally. Could you help me how I can see and test the doc.crds.dev changes locally? ( it seems https://github.com/crdsdev/doc is not that active anymore, I was not able to find info on any of their docs ).
> 
> 
> 
> 
> 
> Second question, is there any documentation that I can reference  on what the expected `description` should be? 


@jameskim0987 doc.crds.dev is the latent package afaik. I think you could use Swagger/OpenAPI to visualize the description etc.

You could take a look at ArgoCD-Operator or other RBAC implementations, but there is no "right" description. It should be concise and easy to understand.
